spring:
  data:
    mongodb:
      database: journaldb
      uri: mongodb+srv://admin:admin@cluster0.osb17.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      port: 27017
      auto-index-creation: true